FORMAT: 1A

# La Testa API
La Testa API is an example API connected as GitHub <-> Apiary.

# Group Everything
There is a lot of stuff inhere.

## Various things [/things]
### List all the things [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Tree"
        }, {
          "id": 2, "name": "Castle"
        }]

### Create a thing [POST]
+ Request (application/json)

        { "name": "Butter" }

+ Response 201 (application/json)

        { "id": 3, "name": "Butter" }

## One thing [/notes/{id}]
A single thing to read about

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the thing

### Show me one thing [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name": "Castle" }
